# RealTradR Production Configuration

# Environment: production, development, testing
environment: production

# Broker Configuration
broker:
  default: alpaca  # Default broker to use
  alpaca:
    api_key: ${ALPACA_API_KEY}  # Set in environment variables
    api_secret: ${ALPACA_API_SECRET}
    paper_trading: false  # Set to true for paper trading
    base_url: https://api.alpaca.markets
    data_url: https://data.alpaca.markets
  ibkr:
    tws_port: 7496  # 7496 for live, 7497 for paper
    tws_host: 127.0.0.1
    client_id: ${IBKR_CLIENT_ID}
    paper_trading: false

# Database Configuration
database:
  url: ${DATABASE_URL}
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800
  echo: false

# Redis Configuration (for caching)
redis:
  url: ${REDIS_URL}
  ttl: 3600  # Default TTL for cached items in seconds

# AI Strategy Configuration
ai:
  # Signal weights
  sentiment_weight: 0.3
  technical_weight: 0.4
  ml_weight: 0.3
  
  # Feature toggles
  use_sentiment: true
  use_technical: true
  use_ml_models: true
  use_market_regime: true
  
  # Model configuration
  model_update_frequency: daily  # hourly, daily, weekly
  model_path: ./models/production
  
  # Sentiment analysis
  sentiment:
    sources: ["twitter", "reddit", "news"]
    twitter_weight: 0.4
    reddit_weight: 0.3
    news_weight: 0.3
    min_confidence: 0.6
  
  # Technical indicators
  technical:
    indicators: ["sma", "ema", "macd", "rsi", "bollinger", "atr", "obv"]
    lookback_periods: [20, 50, 200]
    
  # Machine learning
  ml:
    models: ["lstm", "ensemble"]
    prediction_horizon: 5  # days
    training_lookback: 1000  # days
    retraining_frequency: weekly  # daily, weekly, monthly
    feature_importance_threshold: 0.05

# Risk Management
risk:
  stop_loss_pct: 2.0
  take_profit_pct: 5.0
  max_drawdown_pct: 25.0
  risk_free_rate: 0.02
  max_correlation: 0.7
  position_sizing: "kelly"  # equal, kelly, volatility
  max_position_pct: 20.0
  portfolio_var_limit: 3.0  # Value at Risk limit (%)
  max_open_positions: 10

# Trading Parameters
trading:
  symbols: ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "TSLA", "JPM", "V", "JNJ"]
  cash_limit: 100000.0
  trading_hours:
    start: "09:30"  # Eastern Time
    end: "16:00"    # Eastern Time
  trading_days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
  execution:
    order_type: "market"  # market, limit
    time_in_force: "day"  # day, gtc, ioc
    slippage_model: "fixed"  # none, fixed, proportional
    slippage_value: 0.001  # 0.1%

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  workers: 4
  timeout: 60
  rate_limit: 100  # requests per minute
  cors_origins: ["https://yourdomain.com"]

# Security
security:
  jwt_secret: ${JWT_SECRET}
  jwt_algorithm: "HS256"
  jwt_expiration_minutes: 60
  password_hash_algorithm: "bcrypt"
  bcrypt_rounds: 12

# Logging Configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: ./logs/realtradR.log
  max_size: 10485760  # 10 MB
  backup_count: 10
  log_to_console: true
  log_to_file: true

# Monitoring
monitoring:
  prometheus_endpoint: /metrics
  health_check_endpoint: /health
  performance_tracking: true
  alert_on:
    error_rate: 0.01  # Alert if error rate exceeds 1%
    response_time: 500  # Alert if response time exceeds 500ms
    drawdown: 10.0  # Alert if drawdown exceeds 10%
    api_failures: true

# Caching
caching:
  market_data_ttl: 300  # 5 minutes
  technical_indicators_ttl: 3600  # 1 hour
  sentiment_data_ttl: 1800  # 30 minutes
  ml_predictions_ttl: 3600  # 1 hour

# Performance Optimization
performance:
  use_multiprocessing: true
  max_workers: 4
  batch_size: 100
  use_gpu: true  # Set to false if no GPU available
  memory_limit: 4096  # MB

# Disaster Recovery
disaster_recovery:
  auto_shutdown_on_drawdown: 25.0  # % drawdown to trigger shutdown
  backup_frequency: daily  # hourly, daily, weekly
  backup_retention_days: 30
  circuit_breakers:
    max_loss_per_trade: 5.0  # %
    max_loss_per_day: 10.0  # %
    max_consecutive_losses: 5
